[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]