# Generated by Django 3.2.9 on 2021-12-01 11:15

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('all_time_high', '0002_auto_20211201_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltimehighrate',
            name='all_time_high_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                      validators=[django.core.validators.DecimalValidator(10, 2),
                                                  django.core.validators.MinValueValidator(Decimal('0.0'))],
                                      verbose_name='Tüm Zamanların En Yüksek Kuru'),
        ),
        migrations.AlterField(
            model_name='alltimehighrate',
            name='excahnge_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                      validators=[django.core.validators.DecimalValidator(10, 2),
                                                  django.core.validators.MinValueValidator(Decimal('0.0'))],
                                      verbose_name='Güncel Kur'),
        ),
    ]
