# Generated by Django 3.2.9 on 2021-12-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0003_auto_20211201_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alltimehighrate',
            old_name='excahnge_rate',
            new_name='exchange_rate',
        ),
    ]
