# Generated by Django 3.2.10 on 2021-12-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0004_rename_excahnge_rate_alltimehighrate_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltimehighrate',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Bildir'),
        ),
    ]
