# Generated by Django 3.2.11 on 2022-01-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0007_auto_20220104_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllTimeHighRate',
        ),
    ]
