# Generated by Django 3.2.11 on 2022-01-15 18:49

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    NotificationSetting = apps.get_model("all_time_high", "NotificationSetting")
    NotificationSetting.objects.get_or_create()


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0009_auto_20220115_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_telegram_enabled', models.BooleanField(default=True, verbose_name='Telegram Bildirimi Açık')),
                ('telegram_notification_interval', models.PositiveSmallIntegerField(default=30, help_text='Dakika bazında', verbose_name="Telegram'a Mesaj Gönderme Sıklığı")),
                ('is_twitter_enabled', models.BooleanField(default=True, verbose_name='Twitter Bildirimi Açık')),
                ('twitter_notification_interval', models.PositiveSmallIntegerField(default=30, help_text='Dakika bazında', verbose_name="Twitter'a Mesaj Gönderme Sıklığı")),
            ],
            options={
                'verbose_name': 'Bildirim Ayarı',
                'verbose_name_plural': 'Bildirim Ayarları',
            },
        ),
        migrations.AlterField(
            model_name='alltimehigh',
            name='last_notification_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Son Bildirim Zamanı'),
        ),
        migrations.AlterField(
            model_name='oneunitdropped',
            name='last_notification_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Son Bildirim Zamanı'),
        ),
        migrations.RunPython(
            create_default_settings,
            reverse_code=migrations.RunPython.noop
        )
    ]

