# Generated by Django 3.2.12 on 2022-02-22 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0010_auto_20220115_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecurrency',
            name='base_symbol',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Para Birimi 1 Sembolü'),
        ),
        migrations.AddField(
            model_name='exchangecurrency',
            name='target_symbol',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Para Birimi 2 Sembolü'),
        ),
    ]
