# Generated by Django 3.2.12 on 2022-02-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0011_auto_20220223_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltimehigh',
            options={'verbose_name': 'Tüm Zamanların En Yüksek Kuru', 'verbose_name_plural': 'Tüm Zamanların En Yüksek Kuru'},
        ),
        migrations.AlterModelOptions(
            name='exchangecurrency',
            options={'verbose_name': 'Para Birimi', 'verbose_name_plural': 'Para Birimleri'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Kur Oranı', 'verbose_name_plural': 'Kur Oranları'},
        ),
        migrations.AlterModelOptions(
            name='oneunitdropped',
            options={'verbose_name': '1 Birim Düşüş', 'verbose_name_plural': '1 Birim Düşüş'},
        ),
    ]
