# Generated by Django 3.2.12 on 2022-02-24 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0013_auto_20220224_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(message='Geçerli bir eposta adresi girin.'), django.core.validators.MaxLengthValidator(255), django.core.validators.MinLengthValidator(5), django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Eposta Adresi')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('last_notified_at', models.DateTimeField(auto_now=True, verbose_name='Son Bildirim Gönderme Tarihi')),
            ],
            options={
                'verbose_name': 'Eposta Adresi',
                'verbose_name_plural': 'Eposta Adresleri',
            },
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='email_list_notification_interval',
            field=models.PositiveSmallIntegerField(default=30, help_text='Dakika bazında', verbose_name="Eposta Listesi'ne Mesaj Gönderme Sıklığı"),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='is_email_list_enabled',
            field=models.BooleanField(default=True, verbose_name='Eposta Listesi Bildirimi Açık'),
        ),
    ]
