# Generated by Django 3.2.12 on 2022-02-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0014_auto_20220224_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationemails',
            name='last_notified_at',
            field=models.DateTimeField(verbose_name='Son Bildirim Gönderme Tarihi'),
        ),
    ]
