# Generated by Django 4.1.4 on 2022-12-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0015_alter_notificationemails_last_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='all_time_high.exchangecurrency', verbose_name='Kur Birimleri'),
        ),
    ]
