# Generated by Django 5.2.7 on 2025-10-09 17:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_time_high', '0016_alter_exchangerate_currency'),
    ]

    def move_oneunitdropped_to_dailylowestprice(apps, schema_editor):
        OneUnitDropped = apps.get_model('all_time_high', 'OneUnitDropped')
        DailyLowestPrice = apps.get_model('all_time_high', 'DailyLowestPrice')
        for oud in OneUnitDropped.objects.all().order_by('update_date'):
            DailyLowestPrice.objects.create(
                currency=oud.currency,
                daily_lowest_price=oud.exchange_rate,
                update_date=oud.update_date,
                notify=oud.notify,
                last_notification_date=oud.last_notification_date
            )

    operations = [
        migrations.CreateModel(
            name='DailyLowestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_lowest_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2), django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Günlük En Düşük Fiyat')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('notify', models.BooleanField(default=False, verbose_name='Bildir')),
                ('last_notification_date', models.DateTimeField(editable=False, null=True, verbose_name='Son Bildirim Zamanı')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all_time_high.exchangecurrency', verbose_name='Kur Birimleri')),
            ],
            options={
                'verbose_name': 'Günlük En Düşük Fiyat',
                'verbose_name_plural': 'Günlük En Düşük Fiyat',
            },
        ),
        migrations.RunPython(move_oneunitdropped_to_dailylowestprice, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='OneUnitDropped',
        ),
    ]
